apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
      protocol: TCP