apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30003
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672